### ISSUE TITLE
Delta money did not match scanned messages

### ISSUE THREAD

**Issue by Pocokk** [AaronV-T/AutoBiographer#21]
Title.

I'm getting this error message in the chat from time-to-time when someone in the party loot gold from the mobs.

Currently using the latest version of the addon.

Also off-topic/side-question: I see plenty of issues/features that you want to fix/implement, will you do them in the near future?

**Comment by Pocokk** [comment]
Bump, is the addon abandoned?

**Comment by AaronV-T** [comment]
Hey. Sorry for the delayed response, I don't really pay attention to the Github issues since everyone else who has run into issues has reported on the Curseforge page. The addon is not abandoned but it's not a major focus anymore so I probably won't ever get to a lot of the things I had hoped, but I will try to fix bugs for people.

Anyway, that message should only ever occur if the addon thinks you're at a mailbox. How often do you get the messages? Can you share any screenshots to help me debug?

**Comment by Pocokk** [comment]
I noticed it in dungeons when in the party someone loots the dead mobs.

**Comment by AaronV-T** [comment]
This should be fixed in the latest version (3.0.3)
